<a href="https://colab.research.google.com/github/BhagyaC/blog/blob/main/simple_transformers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This notebook is some simple transformer related experiments

In [1]:
#installing the transofmers

In [ ]:
!pip install transformers

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM
tknzr = AutoTokenizer.from_pretrained("distilgpt2")

In [ ]:
model = AutoModelForCausalLM.from_pretrained("distilgpt2", output_hidden_states=True)

In [15]:
sample_text = "I want to be a machine learning"

In [16]:
#tokenise the input sententece
input = tknzr.encode(sample_text, return_tensors="pt")

In [17]:
input

tensor([[  40,  765,  284,  307,  257, 4572, 4673]])

In [28]:
output = model.generate(input, max_length=8,do_sample=False)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [29]:
output

tensor([[  40,  765,  284,  307,  257, 4572, 4673, 4572]])

In [30]:
tknzr.decode(output[0])

'I want to be a machine learning machine'

Here the predicted word after machine learning is again machine which is not so good. Let us see how the word to vectors works

In [31]:
input

tensor([[  40,  765,  284,  307,  257, 4572, 4673]])

In [32]:
#this is the vectorised input now let us see how they look them converted into tokends

In [33]:
tknzr.convert_ids_to_tokens(input[0])

['I', 'Ġwant', 'Ġto', 'Ġbe', 'Ġa', 'Ġmachine', 'Ġlearning']

Earlier in our blog we learned that the embedding vector size will be different for differntr models. to know what all are the dimention we can use "wte" function which will return the number of tokens in the vocabulary and the dimenstion of the model

In [34]:
model.transformer.wte

Embedding(50257, 768)

Previously when we converted the input to the tokens we got some values correspoding to each work right? Let us look into the embedding for those tokens, for example 4572 is for machine

In [38]:
import torch

In [41]:
model.transformer.wte(torch.tensor(4572))

tensor([ 5.0140e-02, -3.9427e-02,  5.8163e-02,  8.9592e-03, -4.7968e-02,
        -7.3724e-02, -3.5826e-01,  2.5049e-02, -7.0663e-02,  1.2497e-02,
         2.0787e-01, -1.0791e-01,  4.5138e-03,  1.1096e-01,  8.3473e-02,
         5.2399e-02,  4.6622e-02,  4.5274e-02,  1.0219e-01,  8.2677e-02,
        -3.0611e-03, -1.3619e-01,  2.9104e-02,  4.0383e-02, -1.0709e-01,
         9.5735e-02,  2.4363e-01,  1.6260e-01, -2.8777e-02,  1.5653e-01,
         7.6510e-02,  7.5093e-02,  3.0166e-01,  4.8214e-03, -5.8404e-02,
         4.7402e-02, -3.1573e-01,  1.2504e-01,  6.4323e-02, -1.9254e-01,
         6.3028e-02,  1.7854e-02, -1.1224e-01,  3.2452e-04,  1.0550e-01,
         7.2170e-02,  1.8547e-01, -1.5653e-02, -1.7186e-01, -9.1829e-02,
        -3.1259e-02,  2.7338e-02,  8.9431e-02, -1.9080e-02, -9.0623e-02,
        -4.1314e-01,  2.2463e-01,  3.5204e-02, -4.4846e-02,  4.3254e-02,
         9.0543e-02,  1.7040e-01,  9.8413e-02,  5.0725e-02,  3.3914e-02,
         2.6470e-01, -2.3209e-01, -1.3297e-01,  1.4

Now this is the vector representation for word machine using transformer algorithms